### ISSUE TITLE
IC0301: Canister rdmx6-jaaaa-aaaaa-aaadq-cai not found after Login click

### ISSUE THREAD

**Issue by Darkwing4** [letmejustputthishere/ii_integration_example#1]
Hello. I cloned your repository from the link provided in [this](https://internetcomputer.org/docs/current/developer-docs/web-apps/user-login/internet-identity/integrate-internet-identity) tutorial. After that, I executed commands from the next step of the tutorial:

dfx deps deploy
dfx deploy

Here's the terminal output: 
Please note the error: Failed to read pulled.json. Please (re)run dfx deps pull.
<details><summary>Details</summary>
<p>
dd@main-pc:~/ii_integration_example$ dfx deps deploy
Error: Failed to read pulled.json. Please (re)run `dfx deps pull`.
Caused by: Failed to read pulled.json. Please (re)run `dfx deps pull`.
  Failed to parse contents of /home/dd/ii_integration_example/deps/pulled.json as json: missing field `wasm_hash_download` at line 9 column 5

dd@main-pc:~/ii_integration_example$ dfx deps pull
Fetching dependencies of canister rdmx6-jaaaa-aaaaa-aaadq-cai...
Found 1 dependencies:
rdmx6-jaaaa-aaaaa-aaadq-cai
Pulling canister rdmx6-jaaaa-aaaaa-aaadq-cai...

dd@main-pc:~/ii_integration_example$ dfx deps deploy
Creating canister: rdmx6-jaaaa-aaaaa-aaadq-cai (internet_identity)
Installing canister: rdmx6-jaaaa-aaaaa-aaadq-cai (internet_identity)

dd@main-pc:~/ii_integration_example$ dfx deploy
Deploying all canisters.
All canisters have already been created.
Building canisters...
Building frontend...
WARN: Building canisters before generate for Motoko
Generating type declarations for canister internet_identity:
  /home/dd/ii_integration_example/src/declarations/internet_identity/internet_identity.did.d.ts
  /home/dd/ii_integration_example/src/declarations/internet_identity/internet_identity.did.js
  /home/dd/ii_integration_example/src/declarations/internet_identity/internet_identity.did
Generating type declarations for canister ii_integration_frontend:
  /home/dd/ii_integration_example/src/declarations/ii_integration_frontend/ii_integration_frontend.did.d.ts
  /home/dd/ii_integration_example/src/declarations/ii_integration_frontend/ii_integration_frontend.did.js
  /home/dd/ii_integration_example/src/declarations/ii_integration_frontend/ii_integration_frontend.did
Generating type declarations for canister ii_integration_backend:
  /home/dd/ii_integration_example/src/declarations/ii_integration_backend/ii_integration_backend.did.d.ts
  /home/dd/ii_integration_example/src/declarations/ii_integration_backend/ii_integration_backend.did.js
  /home/dd/ii_integration_example/src/declarations/ii_integration_backend/ii_integration_backend.did

Installing canisters...
Upgrading code for canister ii_integration_backend, with canister ID bkyz2-fmaaa-aaaaa-qaaaq-cai
Module hash e5d0fa8491f68d3744f851d4a94275d3460154adc39b92a345204f627a88cf42 is already installed.
Upgrading code for canister ii_integration_frontend, with canister ID bd3sg-teaaa-aaaaa-qaaba-cai
Module hash 32e92f1190d8321e97f8d8f3e793019e4fd2812bfc595345d46d2c23f74c1ab5 is already installed.
Uploading assets to asset canister...
Fetching properties for all assets in the canister.
Starting batch.
Staging contents of new and changed assets in batch 2:
  /index.html (674 bytes) sha 7177d2a833fea5a8a74ee32f3b929f2943a0e15bd0832a2822cf5bb2fcbe2fcf is already installed
  /index.html (gzip) (337 bytes) sha 4649dd8f71c5aa6213ee946461f4a2d96464939f7a121efa31db5f42560e7922 is already installed
  /favicon.ico (15406 bytes) sha 4e8d31b50ffb59695389d94e393d299c5693405a12f6ccd08c31bcf9b58db2d4 is already installed
  /sample-asset.txt (25 bytes) sha a8cb224267ed57627d6713956191f6558a8b32117d7cfea8704f38f647069b84 is already installed
  /main.css (574 bytes) sha 0e4283467e24312e84cda0d6ba327e9d151e3b6b9e2c259c91f25fc91631ac13 is already installed   
  /main.css (gzip) (304 bytes) sha 35afda5f8734d99a2bc786d2aa77837ff37be235a696cc394b435dc092f8215e is already installed
  /logo2.svg (15176 bytes) sha 7dd16e40c92b64f317dcf3910b91c07bbf54228668dcfa44e15213fb91d7d640 is already installed
  /index.js (gzip) 1/1 (188562 bytes) sha 9b3bf27f4a96d243398e757488e63698321e7445d2c2c54670eec69450f7d156 (with 7 headers)
  /index.js 1/1 (800006 bytes) sha b9c6cdc27fc9b836029e7d1ec0f3d4ab3b600c2490ecc8dd142b3e022769d21f (with 7 headers)
  /index.js.map (gzip) 1/1 (193338 bytes) sha e04a65cfd0fb1a278fe662183d7f2eb373bd1be8af79aeec4ae145525ce45c47 (with 7 headers)
  /index.js.map 1/1 (849238 bytes) sha f5b2fe141a387c9c88f0d66ace98b230094ff7ac35426ce0e8493ed664ec6551 (with 7 headers)
Committing batch.
Committing batch with 4 operations.
Deployed canisters.
URLs:
  Frontend canister via browser
    ii_integration_frontend:
      - http://127.0.0.1:4943/?canisterId=bd3sg-teaaa-aaaaa-qaaba-cai
      - http://bd3sg-teaaa-aaaaa-qaaba-cai.localhost:4943/
  Backend canister via Candid interface:
    ii_integration_backend: http://127.0.0.1:4943/?canisterId=be2us-64aaa-aaaaa-qaabq-cai&id=bkyz2-fmaaa-aaaaa-qaaaq-cai
    internet_identity: http://127.0.0.1:4943/?canisterId=be2us-64aaa-aaaaa-qaabq-cai&id=rdmx6-jaaaa-aaaaa-aaadq-cai

</p>
</details> 

When deploying the canister, I encounter the error IC0301: Canister rdmx6-jaaaa-aaaaa-aaadq-cai not found after the Login click.
![image](https://github.com/letmejustputthishere/ii_integration_example/assets/22674637/019dd189-3565-49f1-9e10-808ada55217b)

At first glance, the project seems identical to the tutorial. Here is the II configuration in my dfx.json:

"internet_identity": {
  "type": "pull",
  "id": "rdmx6-jaaaa-aaaaa-aaadq-cai"
},
I tried different configurations, but that didn't yield any results. I also tried changing the addresses in the js on the button, but that was also unsuccessful. Could you advise the steps to deploy this example on a local machine? DFX is set up on WSL2.

**Comment by letmejustputthishere** [comment]
Hey,
thanks for this report. May I ask what version of `dfx` you are running?

**Comment by Darkwing4** [comment]
Hi, 
my dfx version is 0.18.0

I apologize for the report without a version, I was tired)

**Comment by Darkwing4** [comment]
The issue is no longer relevant; I completely cleared all caches and ran DFX with the `--clean` flag, and now the login button works as it should. I can register and complete the registration process. I'm not sure what the problem was. Is there a difference from which directory I run `dfx start`?

**Comment by letmejustputthishere** [comment]
Great to hear! Using `--clear` and if necessary deleting the projects `.dfx` resolves most issues. AFAIK `dfx` runs the replica globally and not per project, so it shouldn't make a difference.
